# Final Project Part 1 - Proposal

Ashley Suiter

For my final project, I will be investigating conflicts in the Middle East primarily using the the Armed Conflict Location and Event Dataset (ACLED.)

**Hypothesis, Assumptions, and Goals**

I intend to use this dataset to identify if violent events such as Battles or Remote violence can be predicted using the occurance of peaceful events such as protests, the location of occurances, primary actors, and seasonality. This information could be particularly useful for identifying the need for peacekeeping operations or for predicting increased terrorist activities in areas where the U.S. military is operating. 


**Risks and Limitations**

The primary limitation of using this dataset is the limited timeframe, as there is just about 3.5 years of data. However, this may be beneficial due to the turmoil in the region as long-term trends may not be as predictive as more current events.  It is possible that the methodolgy is only valid in particular countries or when specific actors are present in the region.  These aspects will be explored during the analysis. 

**The Dataset**

The ACLED dataset contains records of conflicts, political violence and protests; including the dates, actors, types of violence, locations, and fatalities.  This particular dataset consists of all events that occured between January 2016 and April 2020, in the Middle East. 

**Possible Additional Analysis**
Depending time and resources terrorist forum data may also be used as a predictor of violent events.  The forum data contains ip addresses, location, country, discussion title, room type and device type.

 Source: 
        “ACLED. (2017). “Armed Conflict Location & Event Data Project (ACLED) Codebook, 2017.””

In [43]:
import pandas as pd

ACLED = pd.read_csv('C:/Users/Ashley/Desktop/General_Assembly/final_project-master/ashley_suiter_final_project/data/MiddleEast_2016-2019_Apr20.csv', encoding='latin-1', low_memory=False)

# Other potentially useful datasets
pop = pd.read_csv('C:/Users/Ashley/Desktop/General_Assembly/final_project-master/ashley_suiter_final_project/data/population_table.csv', encoding='latin-1')  # 2018 population
MNBR = pd.read_csv('C:/Users/Ashley/Desktop/General_Assembly/final_project-master/ashley_suiter_final_project/data/MNBR_JoinedInfo.csv', encoding='latin-1') # Terrorist forum data
Shamikh = pd.read_csv('C:/Users/Ashley/Desktop/General_Assembly/final_project-master/ashley_suiter_final_project/data/Shamikh_JoinedInfo.csv', encoding='latin-1') # Terrorist forum data

In [44]:
#Visaulize the information within the ACLED dataset using the first 5 rows
ACLED.head()

,ISO,EVENT_ID_CNTY,EVENT_ID_NO_CNTY,EVENT_DATE,YEAR,TIME_PRECISION,EVENT_TYPE,SUB_EVENT_TYPE,ACTOR1,ASSOC_ACTOR_1,...,ADMIN3,LOCATION,LATITUDE,LONGITUDE,GEO_PRECISION,SOURCE,SOURCE_SCALE,NOTES,FATALITIES,TIMESTAMP
0,48,BHR323,323,01-January-2016,2016,1,Protests,Peaceful protest,Protesters (Bahrain),NaN,...,NaN,Ad Diraz,26.218,50.471,1,Press TV,National,Small protest have been held in the village of...,0,1552577233
1,48,BHR324,324,01-January-2016,2016,1,Protests,Peaceful protest,Protesters (Bahrain),NaN,...,NaN,Al Maamir,26.133,50.609,1,Press TV,National,Small protest have been held in the village of...,0,1552577233
2,48,BHR325,325,01-January-2016,2016,1,Protests,Peaceful protest,Protesters (Bahrain),NaN,...,NaN,Nabih Sehla,26.183,50.585,1,Press TV,National,Small protest have been held in the village of...,0,1552577233
3,48,BHR327,327,01-January-2016,2016,1,Protests,Excessive force against protesters,Protesters (Bahrain),NaN,...,NaN,Abu Saybi,26.218,50.507,1,Middle East Eye,International,Bahrainis took part in an anti-regime protest ...,0,1552577233
4,48,BHR328,328,01-January-2016,2016,1,Protests,Excessive force against protesters,Protesters (Bahrain),NaN,...,NaN,Ash Shakhurah,26.215,50.507,1,Middle East Eye,International,Bahrainis took part in an anti-regime protest ...,0,1552577233

In [45]:
ACLED.shape

(133959, 29)

In [46]:
# Understand the datatypes of each column in the dataset
# Some fields, such as date and timestamp, will need to be transformed to another datatype to be useful.
ACLED.dtypes

ISO                   int64
EVENT_ID_CNTY        object
EVENT_ID_NO_CNTY      int64
EVENT_DATE           object
YEAR                  int64
TIME_PRECISION        int64
EVENT_TYPE           object
SUB_EVENT_TYPE       object
ACTOR1               object
ASSOC_ACTOR_1        object
INTER1                int64
ACTOR2               object
ASSOC_ACTOR_2        object
INTER2                int64
INTERACTION           int64
REGION               object
COUNTRY              object
ADMIN1               object
ADMIN2               object
ADMIN3               object
LOCATION             object
LATITUDE            float64
LONGITUDE           float64
GEO_PRECISION         int64
SOURCE               object
SOURCE_SCALE         object
NOTES                object
FATALITIES            int64
TIMESTAMP             int64
dtype: object

In [47]:
# Descriptive statistics of numeric fields within the dataset
ACLED.describe()

,ISO,EVENT_ID_NO_CNTY,YEAR,TIME_PRECISION,INTER1,INTER2,INTERACTION,LATITUDE,LONGITUDE,GEO_PRECISION,FATALITIES,TIMESTAMP
count,133959.000000,133959.000000,133959.000000,133959.000000,133959.000000,133959.000000,133959.000000,133959.000000,133959.000000,133959.000000,133959.000000,1.339590e+05
mean,683.788510,18316.431087,2017.319904,1.045745,3.755910,2.180287,30.951157,29.720179,40.451882,1.393494,2.099583,1.552762e+09
std,207.941423,16689.127283,0.900319,0.225133,2.962781,2.593052,24.394068,8.815149,4.402622,0.568447,6.897289,6.003785e+05
min,48.000000,1.000000,2016.000000,1.000000,1.000000,0.000000,10.000000,12.631000,26.306000,1.000000,0.000000,1.552576e+09
25%,682.000000,4261.000000,2017.000000,1.000000,1.000000,0.000000,12.000000,17.493000,36.620000,1.000000,0.000000,1.552577e+09
50%,760.000000,13833.000000,2017.000000,1.000000,2.000000,1.000000,18.000000,33.983000,40.727000,1.000000,0.000000,1.552577e+09
75%,792.000000,28099.000000,2018.000000,1.000000,8.000000,2.000000,38.000000,35.759000,43.783000,2.000000,1.000000,1.552577e+09
max,887.000000,471339.000000,2019.000000,3.000000,8.000000,8.000000,88.000000,42.027000,62.778000,3.000000,469.000000,1.555977e+09

In [48]:
# Descirbe the object fields within the dataset
ACLED.describe(include = 'object')

,EVENT_ID_CNTY,EVENT_DATE,EVENT_TYPE,SUB_EVENT_TYPE,ACTOR1,ASSOC_ACTOR_1,ACTOR2,ASSOC_ACTOR_2,REGION,COUNTRY,ADMIN1,ADMIN2,ADMIN3,LOCATION,SOURCE,SOURCE_SCALE,NOTES
count,133959,133959,133959,133959,133959,31399,86843,15194,133959,133959,133959,132427,61254,133959,133959,133959,133959
unique,133959,1206,7,25,677,1687,641,1367,1,15,216,1372,356,8729,5332,47,121085
top,SYR29594,07-September-2018,Explosions/Remote violence,Air/drone strike,Military Forces of Syria (2000-),Militia (Pro-Government),Civilians (Syria),Militia (Pro-Government),Middle East,Syria,Hama,Jebel Saman,Central,Mosul,SOHR,Other-Local,Coalition airstrikes hit unknown in Sirwah
freq,1,240,73916,34325,23979,4442,14083,2999,133959,57253,10949,3955,3481,1288,23580,50846,105

In [49]:
ACLED.isna().sum()

ISO                      0
EVENT_ID_CNTY            0
EVENT_ID_NO_CNTY         0
EVENT_DATE               0
YEAR                     0
TIME_PRECISION           0
EVENT_TYPE               0
SUB_EVENT_TYPE           0
ACTOR1                   0
ASSOC_ACTOR_1       102560
INTER1                   0
ACTOR2               47116
ASSOC_ACTOR_2       118765
INTER2                   0
INTERACTION              0
REGION                   0
COUNTRY                  0
ADMIN1                   0
ADMIN2                1532
ADMIN3               72705
LOCATION                 0
LATITUDE                 0
LONGITUDE                0
GEO_PRECISION            0
SOURCE                   0
SOURCE_SCALE             0
NOTES                    0
FATALITIES               0
TIMESTAMP                0
dtype: int64

In [50]:
ACLED.groupby('EVENT_TYPE').agg({'FATALITIES': 'mean'}).sort_values(by='FATALITIES')

                            FATALITIES
EVENT_TYPE
Protests                      0.005678
Riots                         0.109294
Strategic developments        0.131747
Explosions/remote violence    0.909091
Explosions/Remote violence    1.583514
Violence against civilians    2.515413
Battles                       4.642525

In [51]:
MNBR.head()

,Unnamed: 0,active_users,active_users_retrieved_at,forum,forum_id,forum_name,hit_at,id,as_organization,asn,...,translated_room_title,device_type,browser_type,browser_name,browser_producer,browser_version,os_family,os_name,os_producer,os_version
0,0,NaN,NaN,/forums/sites/2a84sb6aW9eUSSX4IGAB5A,2a84sb6aW9eUSSX4IGAB5A,MNBR,2018-12-16T22:46:55,tscrUoC9Wmi79CWU3EnI5w,NaN,NaN,...,Event section and breaking news,Personal computer,Browser,Firefox,Mozilla Foundation,60,Windows,Windows 7,Microsoft Corporation.,6.1
1,1,NaN,NaN,/forums/sites/2a84sb6aW9eUSSX4IGAB5A,2a84sb6aW9eUSSX4IGAB5A,MNBR,2018-12-16T21:13:59,ClXhMlYAXoqTe3mGxUdlGA,NaN,NaN,...,Event section and breaking news,Personal computer,Browser,Firefox,Mozilla Foundation,60,Windows,Windows 7,Microsoft Corporation.,6.1
2,2,NaN,NaN,/forums/sites/2a84sb6aW9eUSSX4IGAB5A,2a84sb6aW9eUSSX4IGAB5A,MNBR,2018-12-16T17:40:49,xRGuhuxeV2Osg9klzF8apA,NaN,NaN,...,Event section and breaking news,Smartphone,Mobile Browser,Chrome Mobile,Google Inc.,70.0.3538.110,Android,Android,"Google, Inc.",7
3,3,NaN,NaN,/forums/sites/2a84sb6aW9eUSSX4IGAB5A,2a84sb6aW9eUSSX4IGAB5A,MNBR,2018-12-16T13:06:23,E-FgAAqHV2ybJ0Wxsj0jtg,NaN,NaN,...,Event section and breaking news,Personal computer,Browser,Firefox,Mozilla Foundation,60,Windows,Windows 7,Microsoft Corporation.,6.1
4,4,NaN,NaN,/forums/sites/2a84sb6aW9eUSSX4IGAB5A,2a84sb6aW9eUSSX4IGAB5A,MNBR,2018-12-14T22:51:57,oJlfdGwhVUy3ykg6oyWiqg,NaN,NaN,...,Event section and breaking news,Personal computer,Browser,Firefox,Mozilla Foundation,60,Windows,Windows 7,Microsoft Corporation.,6.1

In [52]:
Shamikh.head()

,Unnamed: 0,active_users,active_users_retrieved_at,forum,forum_id,forum_name,hit_at,id,as_organization,asn,...,translated_room_title,device_type,browser_type,browser_name,browser_producer,browser_version,os_family,os_name,os_producer,os_version
0,0,NaN,NaN,/forums/sites/XdymfFejVkGvrUiOWy7cQg,XdymfFejVkGvrUiOWy7cQg,Shamikh,2018-12-17T13:34:18,BCxSsq4VXTyPLC6l6uLdwA,NaN,NaN,...,Camp Shomuk,Personal computer,Browser,Firefox,Mozilla Foundation,63,Windows,Windows,Microsoft Corporation.,10
1,1,NaN,NaN,/forums/sites/XdymfFejVkGvrUiOWy7cQg,XdymfFejVkGvrUiOWy7cQg,Shamikh,2018-12-17T08:50:17,cRylZ1oAUlOxlnrxvs6Lpw,NaN,NaN,...,NaN,Personal computer,Browser,Chrome,Google Inc.,70.0.3538.110,Windows,Windows 7,Microsoft Corporation.,6.1
2,2,NaN,NaN,/forums/sites/XdymfFejVkGvrUiOWy7cQg,XdymfFejVkGvrUiOWy7cQg,Shamikh,2018-12-17T00:46:03,7cyeo2IFWumMxZOIMyP_0g,NaN,NaN,...,Computer and Internet Forum,Tablet,Mobile Browser,Mobile Safari,Apple Inc.,11,iOS,iOS,Apple Inc.,11.4.1
3,3,NaN,NaN,/forums/sites/XdymfFejVkGvrUiOWy7cQg,XdymfFejVkGvrUiOWy7cQg,Shamikh,2018-12-16T19:56:26,chCr7tYGXcGRpdsEgvKCXA,NaN,NaN,...,Forum News and Nation Issues,Personal computer,Browser,Chrome,Google Inc.,60.0.3112.90,Windows,Windows 7,Microsoft Corporation.,6.1
4,4,NaN,NaN,/forums/sites/XdymfFejVkGvrUiOWy7cQg,XdymfFejVkGvrUiOWy7cQg,Shamikh,2018-12-16T19:56:06,uria4lFXWBKr6cGtjRzM7Q,NaN,NaN,...,NaN,Personal computer,Browser,Chrome,Google Inc.,60.0.3112.90,Windows,Windows 7,Microsoft Corporation.,6.1

In [53]:
print(Shamikh.describe())
print(Shamikh.describe(include = 'object'))

        Unnamed: 0  active_users  active_users_retrieved_at  as_organization  \
count  18791.00000           0.0                        0.0              0.0
mean    9395.00000           NaN                        NaN              NaN
std     5424.63879           NaN                        NaN              NaN
min        0.00000           NaN                        NaN              NaN
25%     4697.50000           NaN                        NaN              NaN
50%     9395.00000           NaN                        NaN              NaN
75%    14092.50000           NaN                        NaN              NaN
max    18790.00000           NaN                        NaN              NaN

       asn  continent_code      latitude     longitude  organization  port  \
count  0.0             0.0  18532.000000  18532.000000           0.0   0.0
mean   NaN             NaN     29.469458      5.913552           NaN   NaN
std    NaN             NaN     21.663094     36.658268           NaN   NaN
min    NaN             NaN    -34.858100   -157.963700           NaN   NaN
25%    NaN             NaN      0.000000      0.000000           NaN   NaN
50%    NaN             NaN     32.807300      2.329200           NaN   NaN
75%    NaN             NaN     50.116700     28.857500           NaN   NaN
max    NaN             NaN     65.000000    153.024300           NaN   NaN

       region  post  population_2018
count     0.0   0.0     1.201300e+04
mean      NaN   NaN     7.454816e+07
std       NaN   NaN     1.046448e+08
min       NaN   NaN     3.815500e+04
25%       NaN   NaN     9.982709e+06
50%       NaN   NaN     4.200805e+07
75%       NaN   NaN     8.229346e+07
max       NaN   NaN     1.415046e+09
                                       forum                forum_id  \
count                                  18791                   18791
unique                                     1                       1
top     /forums/sites/XdymfFejVkGvrUiOWy7cQg  XdymfFejVkGvrUiOWy7cQg
freq                                   18791                   18791

       forum_name                     hit_at                      id  \
count       18791                      18791                   18561
unique          1                      18526                   18561
top       Shamikh  2018-02-11T13:16:40+00:00  yXKcI9erWwKTm27aQjVaYg
freq        18791                          4                       1

              city         country country_code          domain  \
count         8529           13361        13361           18791
unique         421              89           84            4675
top     Manchester  United Kingdom           GB  uk.virtono.com
freq           719            1811         1811             719

           ip_address  ...         translated_room_title        device_type  \
count           18791  ...                         10263              18791
unique           4550  ...                            28                  5
top     77.81.107.185  ...  Forum News and Nation Issues  Personal computer
freq              719  ...                          4540              14907

       browser_type browser_name    browser_producer browser_version  \
count         18791        18791               18791           18780
unique            4           19                   8             209
top         Browser      Firefox  Mozilla Foundation              52
freq          14925        10213               10409            4723

       os_family    os_name             os_producer os_version
count      18791      18791                   18684      17901
unique         8         23                       7         53
top      Windows  Windows 7  Microsoft Corporation.        6.1
freq       13936       9267                   13936       9267

[4 rows x 32 columns]

In [54]:
Shamikh.columns

Index(['Unnamed: 0', 'active_users', 'active_users_retrieved_at', 'forum',
       'forum_id', 'forum_name', 'hit_at', 'id', 'as_organization', 'asn',
       'city', 'continent_code', 'country', 'country_code', 'domain',
       'ip_address', 'isp', 'latitude', 'longitude', 'organization', 'port',
       'region', 'platform_url', 'post', 'referer', 'user_agent', 'via',
       'room', 'room_id', 'room_title', 'thread', 'thread_id', 'thread_title',
       'translated_thread_title', 'population_2018', 'translated_room_title',
       'device_type', 'browser_type', 'browser_name', 'browser_producer',
       'browser_version', 'os_family', 'os_name', 'os_producer', 'os_version'],
      dtype='object')